# Generated by Django 5.1.4 on 2025-01-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="prescribed_medication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital_app.prescription",
            ),
        ),
    ]
