# Generated by Django 5.1.4 on 2025-01-04 17:40

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_app", "0002_alter_medicalrecord_prescribed_medication"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="department_name_en",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="department_name_ru",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="diagnosis_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="diagnosis_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="treatment_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="treatment_ru",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="working_days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Понедельник", "Понедельник"),
                    ("Вторник", "Вторник"),
                    ("Среда", "Среда"),
                    ("Четверг", "Четверг"),
                    ("Пятница", "Пятница"),
                    ("Суббота", "Суббота"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
    ]
