# Generated by Django 5.1.4 on 2025-01-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_app", "0003_department_department_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="shift_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="shift_start",
            field=models.DateTimeField(),
        ),
    ]
